name: Build, test and deploy

on:
  push:
    branches: [master]
  
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: 8.2

      - name: Create database
        run: touch ./database/database.sqlite

      - name: Copy .env
        run: cp .env.test .env

      - name: Install app
        run: composer install

      - name: Run migrations
        run: php artisan migrate

      - name: Test PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Test PHPUnit
        run: ./vendor/bin/phpunit
      

